// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcaI9ax2GyVSiVg6nkxVzuYVCBrRnliAs',
    appId: '1:807577918032:web:bb2b6c2ea7bca855374f55',
    messagingSenderId: '807577918032',
    projectId: 'chatt-43d0f',
    authDomain: 'chatt-43d0f.firebaseapp.com',
    storageBucket: 'chatt-43d0f.firebasestorage.app',
    measurementId: 'G-GB51PMJX1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtCRQoYknEs10_pd3rmC6z-sUmewT01WI',
    appId: '1:807577918032:android:d2840cb3fa8f702e374f55',
    messagingSenderId: '807577918032',
    projectId: 'chatt-43d0f',
    storageBucket: 'chatt-43d0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz6mMsa4GSqQHpmD2KtTREJH5df4BLYe0',
    appId: '1:807577918032:ios:2a8f2b8b0f795f77374f55',
    messagingSenderId: '807577918032',
    projectId: 'chatt-43d0f',
    storageBucket: 'chatt-43d0f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz6mMsa4GSqQHpmD2KtTREJH5df4BLYe0',
    appId: '1:807577918032:ios:2a8f2b8b0f795f77374f55',
    messagingSenderId: '807577918032',
    projectId: 'chatt-43d0f',
    storageBucket: 'chatt-43d0f.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcaI9ax2GyVSiVg6nkxVzuYVCBrRnliAs',
    appId: '1:807577918032:web:bb77afbd311f365e374f55',
    messagingSenderId: '807577918032',
    projectId: 'chatt-43d0f',
    authDomain: 'chatt-43d0f.firebaseapp.com',
    storageBucket: 'chatt-43d0f.firebasestorage.app',
    measurementId: 'G-39K804FMKP',
  );
}
