// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NuoWr62b1KxGS0gaxspe9c7fTBfYKgc',
    appId: '1:183713911637:web:f6b0b028d9d61fce8315dc',
    messagingSenderId: '183713911637',
    projectId: 'chat-app-d7479',
    authDomain: 'chat-app-d7479.firebaseapp.com',
    storageBucket: 'chat-app-d7479.appspot.com',
    measurementId: 'G-QF4BQK5HH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrS7yF3j6LpRGmmF4KPI4jfPhTBnBeqD8',
    appId: '1:183713911637:android:5be995550faba7f98315dc',
    messagingSenderId: '183713911637',
    projectId: 'chat-app-d7479',
    storageBucket: 'chat-app-d7479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE2qVkFIiH0mY0kLJVRwIlBgUfPgJyRC0',
    appId: '1:183713911637:ios:463266f3e920f6d28315dc',
    messagingSenderId: '183713911637',
    projectId: 'chat-app-d7479',
    storageBucket: 'chat-app-d7479.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE2qVkFIiH0mY0kLJVRwIlBgUfPgJyRC0',
    appId: '1:183713911637:ios:463266f3e920f6d28315dc',
    messagingSenderId: '183713911637',
    projectId: 'chat-app-d7479',
    storageBucket: 'chat-app-d7479.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9NuoWr62b1KxGS0gaxspe9c7fTBfYKgc',
    appId: '1:183713911637:web:cede8fa1c3c07de18315dc',
    messagingSenderId: '183713911637',
    projectId: 'chat-app-d7479',
    authDomain: 'chat-app-d7479.firebaseapp.com',
    storageBucket: 'chat-app-d7479.appspot.com',
    measurementId: 'G-KFK3JZ6DXP',
  );
}
